version: '3.1'

services:
  db:
    image: postgres:latest
    privileged: true
    expose:
      - 5432
    env_file:
      - ./db.env

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5673:5672
      - 15673:15672
    env_file:
      - ./db.env
    networks:
      - rabbitmq_go_net
    depends_on:
      - db

  runserver:
    build:
      context: .
    ports:
      - 8000:8000
    command: bash -c "
      ./wait-for-postgres.sh db
      && python3 manage.py runserver 0.0.0.0:8000
      && celery -A test_task worker -l info -P gevent
      "
    depends_on:
      - rabbitmq

  celery:
    build: .
    command: celery -A test_task worker -l info
#    volumes:
#      - ./backend:/usr/src/app
#    env_file:
#      - ./db.env
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq:rabbitmq@rabbitmq:5673//
      - CELERY_ACCEPT_CONTENT=['json']
      - CELERY_RESULT_SERIALIZER='json'
      - CELERY_TASK_SERIALIZER='json'
      - CELERY_ENABLE_UTC=True
    depends_on:
      - rabbitmq

#  autotests:
#    build:
#      context: .
#    command: bash -c "
#      python3 manage.py test --settings=test_task.settings
#      "
#    depends_on:
#      - rabbitmq

networks:
  rabbitmq_go_net:
    driver: bridge


#&& python3 manage.py makemigrations
#&& python3 manage.py migrate
#&& python3 manage.py create_superuser
#&& celery -A test_task worker -l info -P gevent