version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: postgres
    privileged: true
    expose:
      - 5432
    env_file:
      - ./db.env

  adminer:
    image: adminer:4.7.8-standalone
    container_name: adminer
    restart: always
    ports:
      - 8090:8080
    depends_on:
      - db

  celery:
    build: .
    container_name: celery
#    environment:
#      - CELERY_BROKER_URL=rabbit
    command: celery -A test_task worker --without-mingle -l info
    depends_on:
      - rabbit
    restart: on-failure

  rabbit:
    image: rabbitmq:3-management-alpine
    container_name: rabbit
    ports:
      - 15672:15672
    depends_on:
      - db

  runserver:
    container_name: django
    build:
      context: .
    ports:
      - 8000:8000
    restart: on-failure
    command: bash -c "
      ./wait-for-postgres.sh db
      && python3 manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      - rabbit

#  autotests:
#    build:
#      context: .
#    command: bash -c "
#      python3 manage.py test --settings=test_task.settings
#      "
#    depends_on:
#      - rabbitmq



#&& python3 manage.py makemigrations
#&& python3 manage.py migrate
#&& python3 manage.py create_superuser
#&& celery -A test_task worker -l info -P gevent