version: '3.1'

services:
  db:
    image: postgres:latest
    privileged: true
    expose:
      - 5432
    env_file:
      - ./db.env

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq_go_net
    depends_on:
      - db

  runserver:
    build:
      context: .
    ports:
      - 8000:8000
    command: bash -c "
      ./wait-for-postgres.sh db
      && python3 manage.py makemigrations
      && python3 manage.py migrate
      && python3 manage.py create_superuser
      && python3 manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      - rabbitmq

  autotests:
    build:
      context: .
    command: bash -c "
      python3 manage.py test --settings=test_task.settings
      "
    depends_on:
      - rabbitmq

networks:
  rabbitmq_go_net:
    driver: bridge
