# Generated by Django 4.0.1 on 2022-01-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('counter', models.IntegerField(default=0)),
                ('bitrate', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('counter', models.IntegerField(default=0)),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('counter', models.IntegerField(default=0)),
                ('video_link', models.URLField(max_length=512)),
                ('subtitles_link', models.URLField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('audio_objects', models.ManyToManyField(related_name='pages', to='mainapp.Audio')),
                ('text_objects', models.ManyToManyField(related_name='pages', to='mainapp.Text')),
                ('video_objects', models.ManyToManyField(related_name='pages', to='mainapp.Video')),
            ],
        ),
    ]
