# Generated by Django 4.0.1 on 2022-01-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
                ('counter', models.IntegerField(default=0)),
                ('bitrate', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Audio',
                'verbose_name_plural': 'Audio objects',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
                ('counter', models.IntegerField(default=0)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Text',
                'verbose_name_plural': 'Text objects',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
                ('counter', models.IntegerField(default=0)),
                ('video_link', models.URLField(max_length=512)),
                ('subtitles_link', models.URLField(max_length=512)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Video objects',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
                ('audio_objects', models.ManyToManyField(blank=True, related_name='pages', to='mainapp.Audio')),
                ('text_objects', models.ManyToManyField(blank=True, related_name='pages', to='mainapp.Text')),
                ('video_objects', models.ManyToManyField(blank=True, related_name='pages', to='mainapp.Video')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
