# Generated by Django 4.0.1 on 2022-01-22 08:13
import random
from django.db import migrations


MAX_VIDEO_OBJECTS = 10
MAX_AUDIO_OBJECTS = 15
MAX_TEXT_OBJECTS = 20
MAX_PAGE_OBJECTS = 12


def forward_code(apps, se):
    Video = apps.get_model('mainapp', 'Video')
    Video.objects.bulk_create([Video(
        title=f'Video title {i}',
        video_link=f'http://video{i}.com',
        subtitles_link=f'http://sub{i}.com') for i in range(1, MAX_VIDEO_OBJECTS)]
    )

    Audio = apps.get_model('mainapp', 'Audio')
    Audio.objects.bulk_create([Audio(
        title=f'Audio title {i}',
        bitrate=256) for i in range(1, MAX_AUDIO_OBJECTS)]
    )

    Text = apps.get_model('mainapp', 'Text')
    Text.objects.bulk_create([Text(
        title=f'Text title {i}',
        text=f'text {i}') for i in range(1, MAX_TEXT_OBJECTS)]
    )

    Page = apps.get_model('mainapp', 'Page')
    for i in range(MAX_PAGE_OBJECTS):
        video_quantity = random.randint(1, MAX_VIDEO_OBJECTS)
        page_video = Video.objects.all()[:video_quantity]

        audio_quantity = random.randint(1, MAX_AUDIO_OBJECTS)
        page_audio = Audio.objects.all()[:audio_quantity]

        text_quantity = random.randint(1, MAX_TEXT_OBJECTS)
        page_text = Text.objects.all()[:text_quantity]

        page_obj = Page.objects.create(title=f'Page title {i}')
        page_obj.video_objects.set(page_video)
        page_obj.audio_objects.set(page_audio)
        page_obj.text_objects.set(page_text)


def reverse_code(apps, se):
    Video = apps.get_model('mainapp', 'Video')
    Video.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(code=forward_code, reverse_code=reverse_code)
    ]
