# Generated by Django 4.0.1 on 2022-01-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20220122_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='audio_objects',
            field=models.ManyToManyField(blank=True, related_name='pages_audio', to='mainapp.Audio'),
        ),
        migrations.AlterField(
            model_name='page',
            name='text_objects',
            field=models.ManyToManyField(blank=True, related_name='pages_text', to='mainapp.Text'),
        ),
        migrations.AlterField(
            model_name='page',
            name='video_objects',
            field=models.ManyToManyField(blank=True, related_name='pages_video', to='mainapp.Video'),
        ),
    ]
